//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace json_Upload_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class empjsondata
    {
        public int Eid { get; set; }
        public Nullable<int> numFound { get; set; }
        public Nullable<int> start { get; set; }
        public Nullable<double> maxScore { get; set; }
        public string id { get; set; }
        public string journal { get; set; }
        public string eissn { get; set; }
        public string publication_date { get; set; }
        public string article_type { get; set; }
        public string author_display { get; set; }
        public string @abstract { get; set; }
        public string title_display { get; set; }
        public Nullable<double> score { get; set; }
    }
}
